[project]
name = "heroshiko-backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "accelerate>=1.15.0",
    "diffusers>=0.40.0",
    "einops>=0.8.2",
    "fvcore>=0.1.5.post20221221",
    "huggingface-hub>=1.31.0",
    "insightface>=2.0",
    "mediapipe>=1.0.1",
    "onnxruntime-gpu>=1.30.0",
    "opencv-python>=5.0.0.93",
    "torch>=2.6.0",
    "gradio>=4.44.0",
    "pyyaml>=6.0",
    "torchvision>=0.21.0",
    "transformers>=4.40.0",
    "pyngrok>=8.1.2",
    "python-dotenv>=1.2.3",
]

[[tool.uv.index]]
name = "pytorch-cu124"
url = "https://download.pytorch.org/whl/cu124"
explicit = true

[tool.uv.sources]
torch = { index = "pytorch-cu124" }
torchvision = { index = "pytorch-cu124" }
